name: Scrimmage4
main: me.skylertyler.scrimmage.Scrimmage
version: 0.5
commands:
  cycle:
    description: cycle to the next map!
  myworld:
    description: check what world your are currently on!
    aliases:
    - 'mw'
  region:
    description: checking!
  regions:
    description: tells you all the regions in the </region> tag!
  location:
    description: tells your location!
  myteam:
    description: tells what team you on!
    aliases:
    - 'mt'
  next: 
    description: tells you what the next map is!
    aliases:  
    - 'nm'
    - 'mn'
    - 'nextmap'
  join:
    description: join a team!
    aliases:
    - 'j'
    - 'jt'
    - 'jointeam' 
    - 'tj'
  setnext: 
    description: set the next map!
    aliases: 
    - 'sn'
    - 'setnextmap' 
  rules:
    description: rules for the current map!
    aliases:
    - 'maprules'
    - 'mr'
  contributors: 
    description: contributors for the current map!
    aliases:
    - 'contribs'